#!/bin/bash


########################################################################
### 卸載服務
########################################################################
# 記錄程序崩潰日誌
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.appsupport.cplogd.plist

# 管理系統日誌文件
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.aslmanager.plist

# 顯示初始化設備並顯示錯誤消息
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.crash_mover.plist

# 日誌轉儲和崩潰報告啟動項
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.awdd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.coresymbolicationd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.crashreportcopymobile.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.CrashHousekeeping.plist

# Log 日誌服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.IMLoggingAgent.plist

# 系統程式崩潰訊息
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.DirectoryService.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.Jetsam.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.SafetyNet.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.StackShot.plist

# 系統日誌
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.syslog_relay.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.syslogd.plist

# 診斷服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.diagnosticd.plist

# 基頻崩潰評估
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DumpBasebandCrash.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DumpPanic.plist

# 列印紀錄
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.prdaily.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.printd.plist

# 更新協助管理
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.daily.plist

# 開發者幫助
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DMHelper.plist

# midi/music 數位介面服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.midiserver-ios.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DuetHeuristic-BM.plist

# 相關幫助
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.nehelper.plist

# 檢查外接充電器相容
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.powerlogd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.powerlogHelperd.plist

# 搜尋欄服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.search.appindexer.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.searchd.plist

# 設置 Apple TW 相關服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.touchsetupd.plist


########################################################################
### 必刪服務
########################################################################
# OTA更新服務
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.OTACrashCopier.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.OTAPKIAssetTool.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.OTATaskingAgent.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.softwarebehaviorservicesd.plist

# CIQ 守護程序
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.fseventsd.plist

########################################################################
### 待處理服務
########################################################################
# 通訊紀錄診斷
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ABDatabaseDoctor.plist

# 連接iTunes顯示電話號碼
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.aggregated.addaily.plist

# safari 網路無法驗證提示
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.certui.relay.plist

# 廣告追蹤限制
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.iad.limitadtrackingd.plist

# 印表機裝置輔助
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.mobile.ptp_device_arbitrator.plist

# facetime / imessage 服務
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponderHelper.plist

# 配件相關AV線DOCK等第三方設備服務(耳機充電器沒影響)
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.iap2d.plist

# 管理批配
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.managedconfiguration.teslad.plist

# 電腦連接iPhone上網服務
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.usb.networking.addNetworkInterface.plist
