#!/bin/bash


########################################################################
### 卸載服務
########################################################################
gensrv_fun(){
# 對應功能日誌
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.aggregated.addaily.plist

# 應用程式使用電池百分比
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.aggregated.plist

# 記錄程序崩潰日誌
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.appsupport.cplogd.plist

# 管理系統日誌文件
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.aslmanager.plist

# 顯示初始化設備並顯示錯誤消息
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.crash_mover.plist

# 日誌轉儲和崩潰報告啟動項
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.awdd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.coresymbolicationd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.crashreportcopymobile.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.CrashHousekeeping.plist

# Log 日誌服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.IMLoggingAgent.plist

# 系統程式崩潰訊息
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.DirectoryService.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.Jetsam.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.SafetyNet.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ReportCrash.StackShot.plist

# 系統日誌
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.syslog_relay.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.syslogd.plist

# 診斷服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.diagnosticd.plist

# 基頻崩潰評估
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DumpBasebandCrash.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DumpPanic.plist

# 列印紀錄
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.prdaily.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.printd.plist

# 更新協助管理
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.daily.plist

# 開發者幫助
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DMHelper.plist

# VPN 相關幫助
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.nehelper.plist

# 檢查外接充電器相容紀錄
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.powerlogd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.powerlogHelperd.plist

# 搜尋欄服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.search.appindexer.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.searchd.plist

# 設置 Apple TW 相關服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.touchsetupd.plist

# 定位服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.locationd.plist

# 遊戲中心
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.GameController.gamecontrollerd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.gamed.plist

# 找尋我的iPhone
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.icloud.findmydeviced.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.icloud.fmfd.plist

# iCloud Backup
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.bird.plist

# iCloud 服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.cloudd.plist
# 照片服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.cloudphotod.plist
}

########################################################################
### 必刪服務
########################################################################
delsev_fun(){
# OTA更新服務
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.OTACrashCopier.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.OTAPKIAssetTool.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.OTATaskingAgent.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.softwareupdateservicesd.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.mobile.softwareupdated.plist
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.softwarebehaviorservicesd.plist

# CIQ 守護程序
/bin/rm -rf /System/Library/LaunchDaemons/com.apple.fseventsd.plist
}

########################################################################
### 進階功能選項服務
########################################################################
advsrv_fun(){
# 通訊紀錄診斷
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.ABDatabaseDoctor.plist

# safari 網路驗證提示
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.certui.relay.plist

# 廣告追蹤限制
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.iad.limitadtrackingd.plist

# 印表機裝置輔助
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.mobile.ptp_device_arbitrator.plist

# 配件相關AV線DOCK等第三方設備服務(耳機充電器沒影響)
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.iap2d.plist

# 管理批配
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.managedconfiguration.teslad.plist

# siri 相關服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.assertiond.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.assistant_service.plist

# 家人圈子/通知服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.familycircled.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.familynotificationd.plist

# 相機快取服務
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.AssetCacheLocatorService.plist

# 相機相片相關服務
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.assetsd.nebulad.plist
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.assetsd.plist

# iTunes 同步服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.backupd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.atc.atwakeup.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.atc.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.CallHistorySyncHelper.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.syncdefaultsd.plist

# 藍芽相關服務
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.BlueTool.plist
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.BTServer.avrcp.plist
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.BTServer.le.plist
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.BTServer.map.plist
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.BTServer.pbap.plist
# /bin/launchctl unload /System/Library/LaunchDaemons/com.apple.BTServer.plist

# facetime / imessage 開啟服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponderHelper.plist

# imessage 相關功能服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.idsremoteurlconnectionagent.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.imagent.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.imautomatichistorydeletionagent.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.imavagent.plist

# midi/music 數位介面服務
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.midiserver-ios.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.DuetHeuristic-BM.plist

# 重置選項(恢復原廠設定 建議卸載)
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.mobile.obliteration.plist

# passbook 服務(不使用信用卡可卸載)
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.passd.plist

# appstore ibook 服務 (不用可卸載)
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.storebookkeeperd.plist

# 語音服務 (不用可卸載)
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.voiced.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.voicemail.vmd.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.voicememod.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.VoiceOverTouch.plist
/bin/launchctl unload /System/Library/LaunchDaemons/com.apple.vsassetd.plist
}


###########################################################
msg_fun(){
echo -e ""
echo -e "    $MSG"
echo -e ""
read
}

###########################################################
menu_fun(){
clear
echo -e ""
echo -e "    關閉背景應用服務"
echo -e ""
echo -e "    1) 關閉背景服務"
echo -e ""
echo -e "    2) 進階關閉背景服務(選擇)"
echo -e ""
echo -e "    0) 退出"
echo -e ""
read MENU
[[ "$MENU" ]]

if [ "$MENU" == "1" ]; then
    MSG="已關閉背景應用服務!"
    gensrv_fun
    menu_fun
elif [ "$MENU" == "2" ]; then
    MSG="已關閉背景應用, 包含同步/語音與其他背景應用服務!"
    advsrv_fun
    menu_fun
else
    exit
fi
}

delsev_fun
menu_fun
