#!/bin/bash


IDEV=$(uname -m)
if [ "$IDEV" == "iPhone4,1"]; then
    4S='y'
fi

if [ -f "/usr/bin/multi_kloader" ]; then
   DBOOT='y'
elif  [ -f "/usr/share/CoolBooter/helpers/multi_kloader" ]; then
   CBOOT='y'
else
   echo "deb https://coolbooter.com/ ./" >> /etc/apt/sources.list.d/cydia.list
   apt-get update
   apt-get install com.coolbooter.coolbootercli
   exit
fi

if [ "$DBOOT" == "y"]; then
    if [ "$4S" == "y"]; then
        /usr/bin/4smulti_kloader /iBSS /iBEC
    else
        /usr/bin/multi_kloader /iBSS /iBEC
    fi
elif [ "$CBOOT" == "y"]; then
    if [ "$4S" == "y"]; then
        /usr/share/CoolBooter/helpers/4smulti_kloader /iBSS /iBEC
    else
        /usr/share/CoolBooter/helpers/multi_kloader /iBSS /iBEC
    fi
fi
