#!/bin/bash


find_xpwn_fun(){
clear
echo -e ""
echo -e "    設置 xpwntool 路徑"
echo -e ""
echo -e "    將 xpwntool 拖放到此"
echo -e ""
read XPWN
[[ "$XPWN" ]]

}

set_xpwn_fun(){
if [ -f "/usr/local/bin/xpwntool" ]; then
    XPWN="/usr/local/bin/xpwntool"
elif [ -f "/usr/bin/xpwntool" ]; then
    XPWN="/usr/bin/xpwntool"
else
    find_xpwn_fun
fi

}

menu_fun(){
clear
echo -e ""
echo -e "    取得 KBAG"
echo -e ""
echo -e "    將已加密文件拖放到此"
echo -e ""
read FILE
[[ "$FILE" ]]

$XPWN $FILE null | awk '{print $2}'


}

set_xpwn_fun
menu_fun

