#!/bin/bash


####################################
SAVEPATH="$HOME"/brew-pkg

MAJOR_MAC_VERSION=$(sw_vers -productVersion | awk -F '.' '{print $2}')
if [ "$MAJOR_MAC_VERSION" == "6" ]; then
	CODE=snow_leopard
elif [ "$MAJOR_MAC_VERSION" == "7" ]; then
	CODE=lion
elif [ "$MAJOR_MAC_VERSION" == "8" ]; then
	CODE=mountain_lion
elif [ "$MAJOR_MAC_VERSION" == "9" ]; then
    CODE=mavericks
elif [ "$MAJOR_MAC_VERSION" == "10" ]; then
    CODE=yosemite
elif [ "$MAJOR_MAC_VERSION" == "11" ]; then
    CODE=el_capitan
elif [ "$MAJOR_MAC_VERSION" == "12" ]; then
    CODE=sierra
else
    CODE=darwin
fi

####################################
msg_fun(){
/usr/bin/clear
echo -e "****************************"
echo -e "    brew 套件打包完成"
echo -e "****************************"
echo -e ""
echo -e "    按任意鍵繼續"
echo -e ""

/usr/bin/open $SAVEPATH
main_fun

}

####################################
main_fun(){
/usr/bin/clear
cd /usr/local/Cellar/
echo -e ""
echo -e "****************************"
echo -e "    備份打包 brew 套件"
echo -e "****************************"
echo -e ""
ls
echo -e ""
echo -e "****************************"
echo -e "    選擇要打包的套件"
echo -e ""
echo -e "    按 x 退出"
echo -e ""

read NAME
[[ "$NAME" ]]

if [ "$NAME" == "x" ]; then
    exit
fi

if [ "$NAME" == "" ]; then
	echo "    沒有輸入套件名稱."
    exit
fi

# check
CHECK=$(ls | grep $NAME)
if [ "$CHECK" == "" ]; then
	echo "    沒有找到套件."
    exit
fi

# 清除 .DS_Store
DS=$(find $NAME | grep '.DS_Store')
for i in $DS; do
    rm "$i"
done

# 製作壓縮黨
VER=$(ls $NAME)
mkdir -p "$SAVEPATH"
tar zcvf "$SAVEPATH"/"$NAME"-"$VER"."$CODE".bottle.tar.gz $NAME
msg_fun
}

main_fun
