#!/bin/bash


####################################
SAVEPATH="$HOME"/zip-pkg
VER=$(sw_vers -productVersion | awk -F '.' '{print $2}')

####################################
msg_fun(){
/usr/bin/clear
echo -e "****************************"
echo -e "    zip 套件打包完成"
echo -e "****************************"
echo -e ""
echo -e "    按任意鍵繼續"
echo -e ""

/usr/bin/open $SAVEPATH
main_fun

}

####################################
main_fun(){
/usr/bin/clear
echo -e ""
echo -e "****************************"
echo -e "    打包自編譯套件"
echo -e "****************************"
echo -e ""
echo -e "    選擇要打包的目錄"
echo -e ""
echo -e "    按 x 退出"
echo -e ""

read PATH
[[ "$PATH" ]]

if [ "$PATH" == "x" ]; then
    exit
fi

if [ "$PATH" == "" ]; then
	echo "    沒有輸入目錄."
    exit
fi

NAME=$(/usr/bin/basename $PATH)
DIR=$(/usr/bin/dirname $PATH)

cd $DIR

# 清除 .DS_Store
DS=$(/usr/bin/find $NAME | /usr/bin/grep '.DS_Store')
for i in $DS; do
    /bin/rm "$i"
done

# 製作壓縮黨
/bin/mkdir -p "$SAVEPATH"
/usr/bin/zip -r "$SAVEPATH"/"$NAME"-osx10"$VER".zip $NAME
msg_fun

}

main_fun
