#!/bin/bash


####### Depends ###############################
### pbzx ota openssl xz
### iOS-Utilities: https://github.com/matteyeux/iOS-Utilities
### openssl: brew install openssl
### xz: brew install xz
###############################################

MV=/bin/mv
CAT=/bin/cat
UNZIP=/usr/bin/gunzip
CPIO=/usr/bin/cpio
XAR=/usr/bin/xar
MAKEDIR=/bin/mkdir
CLEAR=/usr/bin/clear

missing_fun(){
$CLEAR
echo -e ""
echo -e "    $TITLE"
echo -e ""
echo -e "    $TEXT"
echo -e ""
read MSG
main_fun
}

set_depends_fun(){
if [ -f "/usr/local/bin/pbzx" ]; then
    PBZX="/usr/local/bin/pbzx"
else
	TITLE="找不到 pbzx ,請重新安裝 iOS-Utilities 與 openssl"
	TEXT="https://github.com/matteyeux/iOS-Utilities"
    missing_fun
fi

if [ -f "/usr/local/bin/ota" ]; then
    OTA="/usr/local/bin/ota"
else
	TITLE="找不到 ota ,請重新安裝 iOS-Utilities 與 openssl"
	TEXT="https://github.com/matteyeux/iOS-Utilities"
    missing_fun
fi

if [ -f "/usr/local/bin/xz" ]; then
    XZ="/usr/local/bin/xz"
else
	TITLE="找不到 xz ,請重新安裝 xz"
	TEXT="$ brew install xz"
    missing_fun
fi

}


msg_fun(){
$CLEAR
echo -e ""
echo -e "    $TITLE"
echo -e ""
echo -e "    $TEXT"
echo -e ""
read MSG

}

pkg_upk_fun(){
$CLEAR
echo -e ""
echo -e "    PKG解壓縮"
echo -e ""
echo -e "    拖放PKG文件到此"
echo -e ""
read PATH
[[ "$PATH" ]]

if [ "$PATH" == "" ]; then
	main_fun
fi

BASE_NAME=$(/usr/bin/basename $PATH)
DIR_NAME=$(/usr/bin/dirname $PATH)
FILE_NAME="${BASE_NAME%.*}"
TARGET="$DIR_NAME/$FILE_NAME"

$MAKEDIR $TARGET
cd $TARGET
$XAR -x -f ../$BASE_NAME

TITLE="PKG 解壓縮"
TEXT="PKG 解壓縮完成!"
msg_fun
main_fun
}

pkg_pk_fun(){
$CLEAR
echo -e ""
echo -e "    PKG壓縮"
echo -e ""
echo -e "    拖放要壓縮的文件所在目錄到此"
echo -e ""
read PATH
[[ "$PATH" ]]

if [ "$PATH" == "" ]; then
	main_fun
fi

BASE_NAME=$(/usr/bin/basename $PATH)

cd $PATH

$XAR -c -f $BASE_NAME".pkg" *

TITLE="PKG 壓縮"
TEXT="PKG 壓縮完成!"
msg_fun
main_fun
}


unbzip2_fun(){
$MV Payload Payload.gz
$UNZIP Payload.gz
$CAT Payload | $CPIO -i
}

unpbzx_fun(){
$PBZX < Payload > Payload.xz
$MV Payload Payload.bak
$XZ --decompress Payload.xz
$OTA -e '*' Payload

}

payload_fun(){
$CLEAR
echo -e ""
echo -e "    Payload解壓縮"
echo -e ""
echo -e "    拖放Payload文件到此"
echo -e ""
read PATH
[[ "$PATH" ]]

if [ "$PATH" == "" ]; then
	main_fun
fi

BASE_NAME=$(/usr/bin/basename $PATH)
DIR_NAME=$(/usr/bin/dirname $PATH)
TARGET="$DIR_NAME/$FILE_NAME"

$MAKEDIR $TARGET
cd $TARGET

FILE_TYPE=$(/usr/bin/file -b Payload | /usr/bin/awk '{print $1}')

if [ "$FILE_TYPE" == "bzip2" ]; then
	unbzip2_fun
else
	set_depends_fun
	unpbzx_fun
fi

TITLE="Payload 解壓縮"
TEXT="Payload 壓縮完成!"
msg_fun
main_fun
}

main_fun(){
$CLEAR
echo -e ""
echo -e "    PKG解壓縮/壓縮"
echo -e ""
echo -e "    1)  解壓縮"
echo -e "    2)  壓縮"
echo -e "    3)  Payload 解壓縮"
echo -e "    0)  EXIT"
echo -e ""

read MENU
[[ "$MENU" ]]

if [ "$MENU" == "1" ]; then
	pkg_upk_fun
elif [ "$MENU" == "2" ]; then
    pkg_pk_fun
elif [ "$MENU" == "3" ]; then
	payload_fun
else
    exit
fi

}

main_fun
