#!/bin/bash


####################################
msg_fun(){
/usr/bin/clear
echo -e "****************************"
echo -e "    zip 套件移除完成"
echo -e "****************************"
echo -e ""
echo -e "    按任意鍵繼續"
echo -e ""
read MSG
main_fun
}

main_fun(){
/usr/bin/clear
cd /usr/local/pkginfo
echo -e ""
echo -e "****************************"
echo -e "    移除自編譯套件"
echo -e "****************************"
echo -e ""
/bin/ls
echo -e ""
echo -e "****************************"
echo -e "    選擇要移除的套件"
echo -e ""
echo -e "    按 x 退出"
echo -e ""

read NAME
[[ "$NAME" ]]

if [ "$NAME" == "x" ]; then
    exit
fi

if [ "$NAME" == "" ]; then
	echo "    沒有輸入套件."
    exit
fi

# 檢查安裝資訊檔
CHECK=$(/bin/ls | /usr/bin/grep $NAME)
if [ "$CHECK" == "" ]; then
    echo "    沒有安裝此套件."
    exit
fi

# 選取移除檔案
FILE=$(/bin/cat /usr/local/pkginfo/$NAME)
for i in $FILE; do
    /bin/rm "$i"
done

# 移除安裝資訊檔
/bin/rm /usr/local/pkginfo/$NAME

msg_fun
}

if [ "$UID" == "0" ]; then
    main_fun
else
    /usr/bin/clear
    echo -e ""
    echo -e "****************************"
    echo -e "    請使用root權限執行"
    echo -e "****************************"
    echo -e ""
    exit
fi

