#!/bin/bash


####### Depends ###############################
### dmg vfdecrypt
###############################################

rm -rf /tmp/ios
mkdir -p /tmp/ios

###############################################
find_path_fun(){
clear
echo -e ""
echo -e "    設置 $FILE 路徑"
echo -e ""
echo -e "    將 $FILE 拖放到此"
echo -e ""
read FPATH
[[ "$FPATH" ]]

}

set_vf_fun(){
if [ -f "/usr/local/bin/vfdecrypt" ]; then
    VF="/usr/local/bin/vfdecrypt"
elif [ -f "/usr/bin/vfdecrypt" ]; then
    VF="/usr/bin/vfdecrypt"
else
	FILE="vfdecrypt"
    find_path_fun
    VF=$FPATH
fi

}

set_dmg_fun(){
if [ -f "/usr/local/bin/dmg" ]; then
    DMG="/usr/local/bin/dmg"
elif [ -f "/usr/bin/dmg" ]; then
    DMG="/usr/bin/dmg"
else
	FILE="dmg"
    find_path_fun
    DMG=$FPATH
fi

}

###############################################

###############################################
msg_fun(){
clear
echo -e ""
echo -e "    $TITLE"
echo -e ""
echo -e "    $TEXT"
echo -e ""
read MSG

}

###############################################
set_key_fun(){
echo -e ""
echo -e "    輸入 KEY"
echo -e ""
read ROM_KEY
[[ "$ROM_KEY" ]]

}

###############################################
set_save_fun(){
echo -e ""
echo -e "    選擇要保存的路徑"
echo -e ""
echo -e "    將保存的路徑拖放到此"
echo -e ""
read SAVE
[[ "$SAVE" ]]

if [ "$SAVE" == "" ]; then
    exit
fi

}

###############################################
set_path_fun(){
echo -e ""
echo -e "    $TITLE"
echo -e ""
echo -e "    將文件拖放到此"
echo -e ""
read ROM
[[ "$ROM" ]]

echo "$ROM" > /tmp/ios/romfile

ROM_PATCH=$(cat /tmp/ios/romfile)
ROM_NAME=$(cat /tmp/ios/romfile | sed s/"\/"/" "/g | tr ' ' '\n' | awk 'END {print}')

if [ "$ROM_PATCH" == "" ]; then
    exit
fi

}

###############################################
rootfs_pk_fun(){
clear
TITLE="設置要壓縮的dmg文件路徑"
set_path_fun
set_save_fun

$DMG build $ROM_PATCH $SAVE"/"$ROM_NAME

TITLE="rootfs"
TEXT="ROOT FileSystem Compression!"
msg_fun

main_fun
}

###############################################
rootfs_upk_fun(){
clear
TITLE="設置已壓縮的dmg文件路徑"
set_path_fun
set_save_fun

$DMG extract $ROM_PATCH $SAVE"/"$ROM_NAME

TITLE="rootfs"
TEXT="ROOT FileSystem Decompression!"
msg_fun

main_fun
}

###############################################
rootfs_dec_fun(){
clear
TITLE="設置dmg加密文件路徑"
set_path_fun
set_save_fun
set_key_fun

$VF -k $ROM_KEY -i $ROM_PATCH -o $SAVE"/"$ROM_NAME

#$DMG extract $ROM_PATCH $SAVE"/"$ROM_NAME

TITLE="rootfs"
TEXT="ROOT FileSystem decrypted!"
msg_fun

main_fun
}

###############################################

main_fun(){
clear
echo -e ""
echo -e "    1) rootfs 解密"
echo -e ""
echo -e "    2) rootfs 解壓縮"
echo -e ""
echo -e "    3) rootfs 壓縮"
echo -e ""
echo -e "    0) EXIT"
echo -e ""
read OPT
[[ "$OPT" ]]

if [ "$OPT" == "1" ]; then
	set_vf_fun
    rootfs_dec_fun
elif [ "$OPT" == "2" ]; then
	set_dmg_fun
    rootfs_upk_fun
elif [ "$OPT" == "3" ]; then
	set_dmg_fun
    rootfs_pk_fun
else
    exit
fi

exit

}

main_fun
