#!/bin/bash



main_fun(){

clear
echo -e ""
echo -e "    設置 XCODE 路徑"
echo -e ""
echo -e "    拖放 XCODE.app 到此"
echo -e ""
read PATH
[[ "$PATH" ]]

XCODEPATH="$PATH/Contents/Developer"
echo "$XCODEPATH"
/usr/bin/sudo /usr/bin/xcode-select --switch $XCODEPATH

}

main_fun
