#!/bin/bash



set_property_fun(){
clear
echo -e ""
echo -e "    賦予屬性"
echo -e ""
echo -e "    1)  賦予文件或目錄隱藏屬性"
echo -e "    2)  去除文件或目錄隱藏屬性"

read MENU
[[ "$MENU" ]]

echo -e ""
echo -e "    拖放文件或目錄到此"
echo -e ""
read FILE
[[ "$FILE" ]]

if [ "$MENU" == "1" ]; then
	sudo chflags hidden $FILE
	main_fun

elif [ "$MENU" == "2" ]; then
	sudo chflags nohidden $FILE
	main_fun
fi
exit

}

main_fun(){

clear
echo -e ""
echo -e "    顯示/隱藏文件或目錄"
echo -e ""
echo -e "    1)  顯示文件或目錄"
echo -e "    2)  隱藏文件或目錄"
echo -e "    3)  賦予文件或目錄屬性"
echo -e "    0)  EXIT"

read MENU
[[ "$MENU" ]]

if [ "$MENU" == "1" ]; then
	defaults write com.apple.finder AppleShowAllFiles -bool true
    KillAll Finder

elif [ "$MENU" == "2" ]; then
    defaults write com.apple.finder AppleShowAllFiles -bool false
    KillAll Finder

elif [ "$MENU" == "3" ]; then
    set_property_fun
else
    exit
fi

}

main_fun
